project_varnish_restart:
    path:     /varnish/restart
    defaults:
        _controller: ProjectBundle:Varnish:restart

project_varnish_compile:
    path:     /varnish/compile
    defaults:
        _controller: ProjectBundle:Varnish:compile