services:
    App\EventListener\HostSubscriber:
        arguments:
            - '@App\Manager\HostManager'
        tags:
            - { name: kernel.event_subscriber }

    App\Twig\TwigExtension:
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: 'twig.extension' }

    App\Certificate\Lescript:
        public: true
        arguments:
          - '%kernel.root_dir%/media/certificate'
          - '@logger'
        calls:
          - ['setContainer', ['@service_container']]

    App\Certificate\CertificateFactory:
        public: true

