parameters:
    locale: en
    varnish_config: /etc/varnish/default.vcl
    varnish_secret: /etc/varnish/secret
    nginx_config: /etc/nginx/nginx.conf
    certificate_path: /var/ssl
    www_path: '%kernel.project_dir%/var/www'

enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user_user
        group:
            type: user_group
        host:
            type: base
            label: Host
            route: app_host_index
            icon: computer
        nginx:
            type: base
            label: Nginx
            route: app_nginx_index
            icon: computer
        varnish:
            type: base
            label: Varnish
            route: app_varnish_index
            icon: computer

sylius_resource:
    resources:
        app.host:
            classes:
                model: App\Entity\Host
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                repository: Enhavo\Bundle\AppBundle\Repository\EntityRepository
                form: App\Form\Type\HostType