version: "1.0"
stages:
    - "clone"
    - "build"
    - "push"
steps:
    main_clone:
        type: "git-clone"
        description: "Cloning main repository..."
        repo: "enhavo/enhavo-proxy"
        revision: "${{CF_BRANCH}}"
        stage: "clone"
    build:
        title: "Building Docker Image"
        type: "build"
        image_name: "enhavo/enhavo-proxy"
        working_directory: "./docker"
        tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
        dockerfile: "Dockerfile"
        stage: "build"
        no_cache: true
        no_cf_cache: true
    push:
        title: "Pushing image to docker hub"
        type: "push"
        image_name: "enhavo/enhavo-proxy"
        registry: "dockerhub"
        candidate: "${{build}}"
        tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
        stage: "push"


