version: '3'
services:
  varnish:
    build: .
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    volumes:
    - "./:/var/www"
  mysql:
    image: mariadb:10.3
    environment:
     MYSQL_ROOT_PASSWORD: root