version: '3'
services:
  proxy:
    image: xqweb/enhavo-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/data/mysql:/var/lib/mysql'