app_nginx_index:
    path: /nginx/index
    defaults:
        _controller: App\Controller\NginxController:indexAction

app_nginx_well_known:
    options:
        expose: true
    path: /.well-known/acme-challenge/{token}
    methods: [GET]
    defaults:
        _controller:  App\Controller\NginxController:wellKnownAction

app_nginx_restart:
    options:
        expose: true
    path: /nginx/restart
    methods: [GET]
    defaults:
        _controller:  App\Controller\NginxController:restartAction

app_nginx_compile:
    options:
        expose: true
    path: /nginx/compile
    methods: [GET]
    defaults:
        _controller:  App\Controller\NginxController:compileAction