app_network_index:
    options:
        expose: true
    path: /app/network/index
    methods: [GET]
    defaults:
        _controller: app.controller.network:indexAction
        _sylius:
            viewer:

app_network_create:
    options:
        expose: true
    path: /app/network/create
    methods: [GET,POST]
    defaults:
        _controller: app.controller.network:createAction
        _sylius:
            redirect: app_network_update
            viewer:

app_network_update:
    options:
        expose: true
    path: /app/network/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: app.controller.network:updateAction
        _sylius:
            viewer:

app_network_table:
    options:
        expose: true
    path: /app/network/table
    methods: [GET,POST]
    defaults:
        _controller: app.controller.network:tableAction
        _sylius:
            viewer:
                columns:
                    id:
                        property: id
                        width: 12
                        label: id
                        type: property

app_network_delete:
    options:
        expose: true
    path: /app/network/delete/{id}
    methods: [POST]
    defaults:
        _controller: app.controller.network:deleteAction

app_network_batch:
    options:
        expose: true
    path: /app/network/batch
    methods: [POST]
    defaults:
        _controller: app.controller.network:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
