app_varnish_index:
    path: /varnish/index
    defaults:
        _controller: App\Controller\VarnishController:indexAction

app_varnish_restart:
    path:     /varnish/restart
    defaults:
        _controller: App\Controller\VarnishController:restartAction

app_varnish_compile:
    path:     /varnish/compile
    defaults:
        _controller: App\Controller\VarnishController:compileAction