enhavo_user_admin:
    resource: "@EnhavoUserBundle/Resources/config/routing/admin.yml"
    prefix: /

enhavo_group_admin_group:
    resource: "@EnhavoUserBundle/Resources/config/routing/admin/group.yml"
    prefix: /
