enhavo_app:
    menu:
        dashboard:
            type: dashboard
        host:
            type: base
            label: Host
            route: project_host_index
            icon: server

enhavo_grid:
    items:

enhavo_translation:
    default_locale: en
    locales:
      en:
    translate: false

sylius_resource:
    resources:
        project.host:
            classes:
                model: ProjectBundle\Entity\Host
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                repository: Enhavo\Bundle\AppBundle\Repository\EntityRepository
                form:
                    default: ProjectBundle\Form\Type\HostType

enhavo_assets:
    require_js:
        paths:
            project:
                location: /bundles/project/js