enhavo_app:
    menu:
        host:
            type: base
            label: Host
            route: project_host_index

enhavo_grid:
    items:

enhavo_translation:
    default_locale: en
    locales:
      en:
    translate: false

sylius_resource:
    resources:
        project.host:
            classes:
                model: ProjectBundle\Entity\Host
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form:
                    default: ProjectBundle\Form\Type\HostType