project_varnish_show_config:
    path:     /varnish/config
    defaults:
        _controller: ProjectBundle:Varnish:showConfig

project_varnish_restart:
    path:     /varnish/restart
    defaults:
        _controller: ProjectBundle:Varnish:restartVarnish

project_varnish_compile:
    path:     /varnish/compile
    defaults:
        _controller: ProjectBundle:Varnish:compileConfig