version: '3'
services:
  proxy:
    container_name: enhavo-proxy
    image: enhavo/proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/enhavo-proxy
  mysql:
    container_name: mysql
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/data/mysql:/var/lib/mysql'