project_default_index:
  path:     /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /admin
    permanent: true

enhavo_nginx:
  resource: "@App/Resources/config/routing/nginx.yml"
  prefix: /

enhavo_host:
  resource: "@App/Resources/config/routing/host.yml"
  prefix: /admin

enhavo_varnish:
  resource: "@App/Resources/config/routing/varnish.yml"
  prefix: /admin

enhavo_dashboard:
  resource: "@App/Resources/config/routing/dashboard.yml"
  prefix: /admin
