parameters:
    locale: 'en'

imports:
    - { resource: services/command.yml }
    - { resource: services/generel.yml }
    - { resource: services/form.yml }
    - { resource: services/manager.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

