ProjectBundle\Entity\Host:
    type: entity
    table: project_host
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        domain:
            type: string
            nullable: true
        https:
            type: integer
            nullable: true
        transferType:
            type: string
            nullable: true
        backendStrategy:
            type: string
            nullable: true
        directorName:
            type: string
            nullable: true
        certPath:
            type: string
            nullable: true
        keyPath:
            type: string
            nullable: true

    oneToMany:
        backends:
            cascade: ['persist', 'remove', 'refresh']
            targetEntity: Backend
            mappedBy: host

    lifecycleCallbacks: {  }
