App\Entity\Network:
  type: entity
  table: app_network
  repositoryClass: App\Repository\NetworkRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO

  lifecycleCallbacks: {  }
