App\Entity\User:
    type: entity
    table: app_user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    lifecycleCallbacks: {  }
