project_default_index:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

enhavo_host:
    resource: "@ProjectBundle/Resources/config/routing/host.yml"
    prefix: /admin