project_default_index:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

enhavo_nginx:
    resource: "@ProjectBundle/Resources/config/routing/nginx.yml"
    prefix: /

enhavo_host:
    resource: "@ProjectBundle/Resources/config/routing/host.yml"
    prefix: /admin

enhavo_varnish:
    resource: "@ProjectBundle/Resources/config/routing/varnish.yml"
    prefix: /admin