services:
    project.form.backend:
        class: ProjectBundle\Form\Type\BackendType
        tags:
          - { name: form.type, alias: 'project_backend' }

    project.varnish.compiler:
        class: ProjectBundle\Varnish\Compiler
        arguments:
            - '@templating'
            - '@filesystem'
            - '%varnish_config%'

    project.nginx.compiler:
        class: ProjectBundle\Nginx\Compiler
        arguments:
            - '@templating'
            - '@filesystem'
            - '%nginx_config%'

    project.subscriber.host_subscriber:
        class: ProjectBundle\EventListener\HostSubscriber
        arguments:
            - '@project.host.host_manager'
        tags:
            - { name: kernel.event_subscriber }

    project.host.host_manager:
        class: ProjectBundle\Host\HostManager

    project.varnish.manger:
        class: ProjectBundle\Varnish\VarnishManager
        arguments:
            - '%varnish_secret%'
            - '@filesystem'