services:
    form.backend:
        class: ProjectBundle\Form\Type\BackendType
        tags:
          - { name: form.type, alias: 'project_backend' }

    subscriber.host_subscriber:
        class: ProjectBundle\EventListener\HostSubscriber
        arguments:
            - '@manager.host'
        tags:
            - { name: kernel.event_subscriber }

    manager.host:
        class: ProjectBundle\Manager\HostManager
        calls:
          - ['setContainer', ['@service_container']]

    manager.varnish:
        class: ProjectBundle\Manager\VarnishManager
        calls:
          - ['setContainer', ['@service_container']]

    manager.nginx:
        class: ProjectBundle\Manager\NginxManager
        calls:
          - ['setContainer', ['@service_container']]

    manager.certificate:
        class: ProjectBundle\Manager\CertificateManager
        calls:
          - ['setContainer', ['@service_container']]


    block.control:
        class: ProjectBundle\Block\ControlBlock
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.block, alias: 'control' }

    certificate.lescript:
        class: ProjectBundle\Certificate\Lescript
        arguments:
          - '%kernel.root_dir%/media/certificate'
          - '@logger'
        calls:
          - ['setContainer', ['@service_container']]


    twig.extension:
        class: ProjectBundle\Twig\TwigExtension
        calls:
          - ['setContainer', ['@service_container']]
        tags:
          - { name: 'twig.extension' }