services:
    project.form.backend:
        class: ProjectBundle\Form\Type\BackendType
        tags:
          - { name: form.type, alias: 'project_backend' }

    project.varnish.compiler:
        class: ProjectBundle\Varnish\Compiler
        arguments:
            - '@templating'
            - '@filesystem'
            - '%varnish_config%'

    project.nginx.compiler:
        class: ProjectBundle\Nginx\Compiler
        arguments:
            - '@templating'
            - '@filesystem'
            - '%nginx_config%'

    project.subscriber.host_subscriber:
        class: ProjectBundle\EventListener\HostSubscriber
        arguments:
            - '@project.host.host_manager'
        tags:
            - { name: kernel.event_subscriber }

    project.host.host_manager:
        class: ProjectBundle\Host\HostManager

    project.varnish.manger:
        class: ProjectBundle\Varnish\VarnishManager
        arguments:
            - '%varnish_secret%'
            - '@filesystem'

    project.nginx.manger:
        class: ProjectBundle\Nginx\NginxManager

    project.block.control:
        class: ProjectBundle\Block\ControlBlock
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.block, alias: 'control' }

    project.certificate.manager:
        class: ProjectBundle\Certificate\Lescript
        arguments:
          - '%kernel.root_dir%/media/certificate'
          - '@logger'
        calls:
          - ['setContainer', ['@service_container']]