services:
    project.form.backend:
        class: ProjectBundle\Form\Type\BackendType
        tags:
          - { name: form.type, alias: 'project_backend' }

    project.subscriber.host_subscriber:
        class: ProjectBundle\EventListener\HostSubscriber
        arguments:
            - '@project.host.host_manager'
        tags:
            - { name: kernel.event_subscriber }

    project.manager.host:
        class: ProjectBundle\Host\HostManager
        calls:
          - ['setContainer', ['@service_container']]

    project.manager.varnish:
        class: ProjectBundle\Varnish\VarnishManager
        calls:
          - ['setContainer', ['@service_container']]

    project.manager.nginx:
        class: ProjectBundle\Nginx\NginxManager
        calls:
          - ['setContainer', ['@service_container']]

    project.block.control:
        class: ProjectBundle\Block\ControlBlock
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.block, alias: 'control' }

    project.certificate.lescript:
        class: ProjectBundle\Certificate\Lescript
        arguments:
          - '%kernel.root_dir%/media/certificate'
          - '@logger'
        calls:
          - ['setContainer', ['@service_container']]

    project.certificate.manager:
        class: ProjectBundle\Certificate\CertificateManager
        calls:
          - ['setContainer', ['@service_container']]


    project.twig.extension:
        class: ProjectBundle\Twig\TwigExtension
        calls:
          - ['setContainer', ['@service_container']]
        tags:
          - { name: 'twig.extension' }