project_nginx_well_known:
    options:
        expose: true
    path: /.well-known/acme-challenge/{token}
    methods: [GET]
    defaults:
        _controller: App:Nginx:wellKnown

project_nginx_restart:
    options:
        expose: true
    path: /admin/nginx/restart
    methods: [GET]
    defaults:
        _controller: App:Nginx:restart

project_nginx_compile:
    options:
        expose: true
    path: /admin/nginx/compile
    methods: [GET]
    defaults:
        _controller: App:Nginx:compile